"""
Django settings for djangoProject3 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
# import dj_database_url
from pathlib import Path
import sys

TESTING = 'test' in sys.argv

if TESTING:
    # Отключаем миграции для тестов
    class DisableMigrations:
        def __contains__(self, app):
            return True

        def __getitem__(self, app):
            return None


    MIGRATION_MODULES = DisableMigrations()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uwpmsr8)j#2isqt-e97q=79-@7-qzeht=*)0^g834fyrm2o*o7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'planner',
]

AUTH_USER_MODEL = 'planner.Users'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoProject3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject3.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'planner',  # 'goalvoyagerdb',
        'USER': 'postgres',  # 'goalvoyagerdb_user',
        'PASSWORD': 'postgres',  # 'ze6KpEyzKkXbE2X5prEhN1Omu0vIZb7V',
        'HOST': 'localhost',   # 'dpg-d0i8d8t6ubrc73d990e0-a.frankfurt-postgres.render.com',
        'PORT': '5432',
    }
}

# DATABASES = {
#     "default": dj_database_url.parse("postgresql://goalvoyagerdb_user:ze6KpEyzKkXbE2X5prEhN1Omu0vIZb7V@dpg"
#                                      "-d0i8d8t6ubrc73d990e0-a.frankfurt-postgres.render.com/goalvoyagerdb")
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = 'media/'
# STATIC_ROOT = os.path.join(BASE_DIR,'/static/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'  # Переход после успешной авторизации
LOGOUT_REDIRECT_URL = 'login'  # Переход после выхода


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Не SSL!
EMAIL_HOST_USER = 'goalvoyager@gmail.com'  # Ваш полный email
EMAIL_HOST_PASSWORD = 'rsye uzvc mfna lfmz'  # 'jorn upfh zyvv uwfe' Пароль приложения
DEFAULT_FROM_EMAIL = 'goalvoyager@gmail.com'


